# Generated by Django 2.0.1 on 2018-03-03 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redovisning', '0003_auto_20180217_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestation',
            name='org_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='redovisning.Organization'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='org_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='redovisning.Organization'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='org_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='redovisning.Organization'),
        ),
        migrations.AlterField(
            model_name='meeeting',
            name='org_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='redovisning.Organization'),
        ),
        migrations.AlterField(
            model_name='member',
            name='org_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='redovisning.Organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='org_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='redovisning.Organization'),
        ),
    ]
